name: Build Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
        - testing
        - production
        - development
        default: development

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: Frontend/my-frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd Frontend/my-frontend
        npm install --legacy-peer-deps
    
    - name: Run ESLint
      run: |
        cd Frontend/my-frontend
        npm run lint
    
    - uses: "kanga333/variable-mapper@master"
      with:
        key: "${{ github.event.inputs.environment || 'development' }}"
        map: |
          {
            "testing": {
              "MEDIA_BUCKET": "${{ secrets.TEST_MEDIA_BUCKET_NAME }}"
            },
            "production": {
              "MEDIA_BUCKET": "${{ secrets.PROD_MEDIA_BUCKET_NAME }}"
            },
            "development": {
              "MEDIA_BUCKET": "${{ secrets.BUILD_MEDIA_BUCKET_NAME }}"
            }
          }
    
    - name: Build application
      run: |
        cd Frontend/my-frontend
        npm run build
      env:
        VITE_AWS_ACCESS_KEY_ID: ${{ secrets.MEDIA_AWS_ACCESS_KEY_ID }}
        VITE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MEDIA_AWS_SECRET_ACCESS_KEY }}
        VITE_S3_BUCKET_NAME: ${{ env.MEDIA_BUCKET }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: Frontend/my-frontend/dist/ 
    
    - name: Print Run ID
      run: echo "The workflow run ID is ${{ github.run_id }}"
    
        