name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
        - testing
        - production
        - development 
        default: development


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: kanga333/variable-mapper@master
      with:
        key: "${{ github.event.inputs.environment }}"
        map: |
          {
            "testing": {
              "S3_BUCKET": "${{ secrets.TEST_HOSTING_BUCKET_NAME }}",
            },
            "production": {
              "S3_BUCKET": "${{ secrets.PROD_HOSTING_BUCKET_NAME }}",
            },
            "development": {
              "S3_BUCKET": "${{ secrets.BUILD_HOSTING_BUCKET_NAME }}",
            }
          }
    - uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./dist
    
    - name: Display structure of downloaded files
      run: ls -R ./dist
    
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Deploy to AWS S3
      run: |
        aws s3 sync ./dist/ s3://${{ secrets.PROD_HOSTING_BUCKET_NAME }} --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2